webtalk_init -webtalk_dir /home/student/Desktop/Verilog-Cores/i2c_master/i2c_master_vivado/i2c_master_vivado.sim/i2c_master_tb/behav/xsim/xsim.dir/i2c_master_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 26 01:25:59 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2960000" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "67573163-a1ed-40aa-bb2f-1bed99321bde" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "10f1c7b6fdc749bdaf655b41b34796fe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "188" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3400G with Radeon Vega Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4100.001 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "4" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "35 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "4 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "38" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.86_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "256148_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2160406202 -regid "" -xml /home/student/Desktop/Verilog-Cores/i2c_master/i2c_master_vivado/i2c_master_vivado.sim/i2c_master_tb/behav/xsim/xsim.dir/i2c_master_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/student/Desktop/Verilog-Cores/i2c_master/i2c_master_vivado/i2c_master_vivado.sim/i2c_master_tb/behav/xsim/xsim.dir/i2c_master_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/student/Desktop/Verilog-Cores/i2c_master/i2c_master_vivado/i2c_master_vivado.sim/i2c_master_tb/behav/xsim/xsim.dir/i2c_master_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
