webtalk_init -webtalk_dir /home/student/Desktop/Cores/i2c_master/i2c_master_vivado/i2c_master_vivado.sim/i2c_master_tb/behav/xsim/xsim.dir/i2c_clk_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 25 21:07:54 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2960000" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "67573163-a1ed-40aa-bb2f-1bed99321bde" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "10f1c7b6fdc749bdaf655b41b34796fe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3400G with Radeon Vega Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4100.001 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "4" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115512_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1185564548 -regid "" -xml /home/student/Desktop/Cores/i2c_master/i2c_master_vivado/i2c_master_vivado.sim/i2c_master_tb/behav/xsim/xsim.dir/i2c_clk_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/student/Desktop/Cores/i2c_master/i2c_master_vivado/i2c_master_vivado.sim/i2c_master_tb/behav/xsim/xsim.dir/i2c_clk_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/student/Desktop/Cores/i2c_master/i2c_master_vivado/i2c_master_vivado.sim/i2c_master_tb/behav/xsim/xsim.dir/i2c_clk_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
