#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Apr 26 01:15:16 EDT 2021
# SW Build 2960000 on Wed Aug  5 22:57:21 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim i2c_master_tb_behav -key {Behavioral:i2c_master_tb:Functional:i2c_master_tb} -tclbatch i2c_master_tb.tcl -log simulate.log"
xsim i2c_master_tb_behav -key {Behavioral:i2c_master_tb:Functional:i2c_master_tb} -tclbatch i2c_master_tb.tcl -log simulate.log

